version: '3.9'

services:
    app:
        image: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
        networks:
            - proxy_network
        ports:
            - ${RSOCKET_PORT}:${RSOCKET_PORT}

        environment:
            SERVER_PORT: ${SERVER_PORT}
            SERVER_ADDR: ${SERVER_ADDR}
            RSOCKET_PORT: ${RSOCKET_PORT}

            KAFKA_BROKER: ${KAFKA_BROKER}
            GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA}

            CASSANDRA_DC: ${CASSANDRA_DC}
            KEYSPACE_NAME: ${KEYSPACE_NAME}
            CASSANDRA_PORT: ${CASSANDRA_PORT}
            CASSANDRA_HOST: ${CASSANDRA_HOST}
            REQUEST_TIMEOUT_FOR_CASSANDRA: ${REQUEST_TIMEOUT_FOR_CASSANDRA}
            CONNECTION_TIMEOUT_FOR_CASSANDRA: ${CONNECTION_TIMEOUT_FOR_CASSANDRA}
            INIT_QUERY_TIMEOUT_FOR_CASSANDRA: ${INIT_QUERY_TIMEOUT_FOR_CASSANDRA}

            CASSANDRA_MAX_REQ: ${CASSANDRA_MAX_REQ}

            CASSANDRA_MAX_CONN_LOCAL: ${CASSANDRA_MAX_CONN_LOCAL}
            CASSANDRA_MAX_CONN_REMOTE: ${CASSANDRA_MAX_CONN_REMOTE}

            CASSANDRA_CORE_CONN_LOCAL: ${CASSANDRA_CORE_CONN_LOCAL}
            CASSANDRA_CORE_CONN_REMOTE: ${CASSANDRA_CORE_CONN_REMOTE}

            TABLETS_GPS_DATA : ${TABLETS_GPS_DATA}

        deploy:
            replicas: ${REPLICAS}
            placement:
                constraints: [node.labels.mgmt != true ]

networks:
    proxy_network:
        external: true
