server:
    port: 9090
    address: localhost

spring:
    rsocket:
        server:
            port: 6060
            address: localhost

variables:
    JWT_VARIABLES:
        ISSUER: ${ISSUER:GpsTabletsServiceApplication}
        SECRET: ${SECRET:rH2JRKHNANolgCdUqsxNKHOAOjaLH2Z4bLyr3lS3ucCJo3q558Nicl8Ksi3fl69GZWC3HuwTX7KDBQQZecqkw==}

    KAFKA_VARIABLES:
        KAFKA_BROKER: 10.254.1.209:9092, 10.254.1.211:9092, 10.254.1.212:9092
        KAFKA_ACKS_CONFIG: ${KAFKA_ACKS_CONFIG:1}
        GROUP_ID_FOR_KAFKA: SSD.GPS.TABLETS_dev
        KAFKA_SENDER_MAX_IN_FLIGHT: ${KAFKA_SENDER_MAX_IN_FLIGHT:1024}

        KAFKA_TOPICS:
            SOS_TOPIC: sos_topic
            ACTIVE_TASK: active_task_dev
            NOTIFICATION: notification_dev
            CAR_TOTAL_DATA: car_total_data_dev
            SOS_TOPIC_FOR_ANDROID_NOTIFICATION: SOS_TOPIC_FOR_ANDROID_NOTIFICATION

    #   https://docs.datastax.com/en/developer/java-driver/3.6/manual/pooling/index.html
    CASSANDRA_VARIABLES:
        CASSANDRA_PORT: ${CASSANDRA_PORT:9042}
        CASSANDRA_HOST: ${CASSANDRA_HOST:localhost}
        CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME:TEST_CLUSTER}

        CASSANDRA_MAX_REQ: ${CASSANDRA_MAX_REQ:1000}
        CASSANDRA_MAX_CONN_LOCAL: ${CASSANDRA_MAX_CONN_LOCAL:10}
        CASSANDRA_MAX_CONN_REMOTE: ${CASSANDRA_MAX_CONN_REMOTE:4}

        CASSANDRA_CORE_CONN_LOCAL: ${CASSANDRA_CORE_CONN_LOCAL:4}
        CASSANDRA_CORE_CONN_REMOTE: ${CASSANDRA_CORE_CONN_REMOTE:2}

        CASSANDRA_READ_TIMEOUT_IN_MILLIS: ${CASSANDRA_READ_TIMEOUT_IN_MILLIS:3000}
        CASSANDRA_CONNECTION_TIMEOUT_IN_MILLIS: ${CASSANDRA_CONNECTION_TIMEOUT_IN_MILLIS:30000}

        CASSANDRA_IDLE_CONN_TIME_IN_SECONDS: ${CASSANDRA_IDLE_CONN_TIME_IN_SECONDS:15}
        CASSANDRA_HEARTBEAT_INTERVAL_IN_SECONDS: ${CASSANDRA_HEARTBEAT_INTERVAL_IN_SECONDS:60}

        CASSANDRA_MAX_REQUESTS_PER_CONNECTION_LOCAL: ${CASSANDRA_MAX_REQUESTS_PER_CONNECTION_LOCAL:32768}
        CASSANDRA_MAX_REQUESTS_PER_CONNECTION_REMOTE: ${CASSANDRA_MAX_REQUESTS_PER_CONNECTION_REMOTE:2000}

        CASSANDRA_RETRY_READ_ATTEMPTS: ${CASSANDRA_RETRY_READ_ATTEMPTS:3}
        CASSANDRA_RETRY_WRITE_ATTEMPTS: ${CASSANDRA_RETRY_WRITE_ATTEMPTS:3}
        CASSANDRA_RETRY_UNAVAILABLE_ATTEMPTS: ${CASSANDRA_RETRY_RUNAVAILABLEATTEMPTS:2}
