package com.example.tabletsproducerservice.constants;

public enum Status {
    LOGIN, LOGOUT,
    START_TO_WORK, STOP_TO_WORK,
    SET_IN_PAUSE, RETURNED_TO_WORK,

    FREE, ARRIVED, BUSY, ATTACHED, FINISHED, AVAILABLE, NOT_AVAILABLE, ACCEPTED, LATE, NOT_ARRIVED,
    CREATED, IN_GARAGE, CANCEL,

    SELF_EMPLOYMENT, NOTIFICATION, ACTIVE_TASK, NEW_CARS
}
