package com.example.tabletsproducerservice.constants;

public enum TaskTypes {
    CARD_102, SELF_EMPLOYMENT, FREE, ESCORT,
    FIND_FACE_PERSON, FIND_FACE_CAR, // FOR TASKS FROM ASSOMIDDIN
    FIND_FACE_EVENT_BODY, FIND_FACE_EVENT_CAR, FIND_FACE_EVENT_FACE // FOR TASKS FROM SHAMSIDDIN
}
